### ISSUE TITLE
Save tab to pocket/bookmarks

### ISSUE THREAD

**Issue by tomas-hartman** [tomas-hartman/clean-the-mess#14]

**Comment by tomas-hartman** [comment]
Prepare ico!

**Comment by tomas-hartman** [comment]
```
www.xyz.com ........ [close-tab] [bookmark-and close] (> [go-to])
```
Add "do not close after bookmarking" to settings #22

**Comment by EstherMoellman** [comment]
> 
> _I have some good news about that, there'll be two buttons: close tab + bookmark-and-close (need to see what FF's bookmark API offers and allows at first though). 
> 

@tomas-hartman , for the FF's bookmark API, if it is useful for you, please take a look at [the add-on I mentioned at the end of my previous comment](https://github.com/jingyu9575/tabs-to-bookmark-groups/releases/tag/v0.0.20190911). This prototype is almost ready (80%), it's meant to "bookmarking/closing" tabs... and that's all... simple and minimalist. I hope you can use it as a source of information or inspiration.

**Comment by tomas-hartman** [comment]
Add icon animation showing that an item was bookmarked.
  - Best case: Use native "added to library" animation.
  - Or: Use an animation over my icon
