### ISSUE TITLE
After removal from details, overview shows one tab still opened

### ISSUE THREAD

**Issue by tomas-hartman** [tomas-hartman/clean-the-mess#23]
After I close all tabs from details overview, overview does not refresh sufficiently, and there might still be one "hanging" tab shown on overview, even thouth the tab is in fact closed.

**Comment by tomas-hartman** [comment]
fix in `refreshOverviewScreen()`

**Comment by nitrram** [comment]
The bug seems to be reciprocal of symptoms: It appears that if you close a tab/a group of tabs using `Clean the mess' , the closed tab(s) are shown in the '10 longest unused' still

**Comment by tomas-hartman** [comment]
Should be fixed now, closing.
