### ISSUE TITLE
Duplicate tabs

### ISSUE THREAD

**Issue by sotakal** [tomas-hartman/clean-the-mess#97]
I'm a terrible tab hoarder and I often open a tab repeatedly, which then gets lost among the other tabs.

A new section 'duplicate tabs' could be useful for monsters like myself to easily find duplicate tabs and 'close all duplicates' from a single place.

Thanks for your consideration.

**Comment by tomas-hartman** [comment]
Thank you for the idea! That is a nice use case and I will think about it. As of now, I only see one problem and that is, which tab should be kept and which one should deleted? And then should I sort the rest of the tabs in some way? Anyways, after solving this user experience related issues, the rest should be quite easy to implement.

**Comment by sotakal** [comment]
Personally, I'd prefer to use keep the original (e.g. oldest) tab and close all duplicates. For the tab sorting - I would keep the remaining tabs intact - really just "close duplicates" and don't do anything else.

**Comment by tomas-hartman** [comment]
Done. Looking forward to releaase this as a part of v2.1.
